services:
  db:
    image: mariadb:12.0.2
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=openplace
      - MARIADB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    image: node:22-alpine
    env_file: ./.env
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "
      npm install &&
      npx prisma migrate deploy &&
      npx prisma generate &&
      npx prisma db push &&
      npm run dev
      "
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  caddy:
    image: caddy:latest
    ports:
      - 80:8000
      - 443:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/srv/frontend
    environment:
      - BACKEND_HOST=app
      - BACKEND_PORT=3000
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend2:
    image: node:22-alpine
    ports:
      - 127.0.0.1:3001:3000
    volumes:
      - .:/app
    working_dir: /app/frontend2
    command: sh -c "CI=1 npx pnpm install && npx pnpm build && node .output/server/index.mjs"
